dist: jammy
notifications:
  email: false
  slack:
    on_success: always
    on_failure: always
    rooms:
      secure: BAsInVJJa+yKD9oQ3G4Y27AHqpY4HQ6QTR37ypa5UfXik/EAZ2d4/g85UwdY2ID/cS/E97bOoMR/nnaij3nsx0BBy79a9/CPqMho+o7zjPvgkJS/QuwCUDKBIJuai7V4UURGvtxEoA3JbaVUBm/TfprZGbFEfT9avhJ9zQIMmLuzslPLK6QAdL6LS2YuhzO/k2PHXDc+UV98sHqvOKPd/oFbIrWdTuB9prYtZytrpiLhNKbqnDg+SeeMjcpzTbAFjo7LsfnAbKgFXRHGobY2ps/cqAyMlFVfBF6rP2odDRXsN9ab5nqFP2G+OClW7t+SPAFSXxZUmntNpohRpQeV5Ny5cKknf/uGfGBiQc1V4JoPSO3Ce4aN6F1ttKx2hTBpzMAlQyYrDhFTYKtNxMUpU7JbbAAaaVBN47xqO14g+pFF+3kbPpHSaHjt3WWJ519mwEHtthvaTi19tTxx9gZiOLashVDPuher8LAEc5L8aRnUnbpcAhA2tNiJF4mI2CZVz0i8R1pAOPpZwM92RYjNOPWzxTwW02kOze8vgBgZZBdCGPm3OP/XgPUlHo4n7UEd7LWT7bhIOkC/VtfA4gol98ujGrc2rHNsjfD2XvkTR5/eDulgMk7j4LkQra3hlw6z2RtKQrR7b40GBll2MoXiQPCyoa1nDNkxWVXnSXaM9Jc=
stages:
- name: BUILD
  if: commit_message !~ /(skip[ _-]build)/
- name: TEST
  if: commit_message !~ /(skip[ _-]test)/
jobs:
  include:
  - stage: BUILD
    language: minimal
    services:
    - docker
    script:
    - bash .travis.build.sh
  - stage: TEST
    language: node_js
    node_js:
    - '16'
    services:
    - mongodb
    env:
    - CC_TEST_REPORTER_ID=db028d86210785c300155b473cba95a59dc3b0c0ababed2737389957372c2092
    install:
    - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
      > ./cc-test-reporter
    - chmod +x ./cc-test-reporter
    - "./cc-test-reporter before-build"
    script:
    - yarn install
    - yarn test
    after_script:
    - "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
